"""Curated semantic icon taxonomy for E01.5.1 Magic Layer+ work."""

from __future__ import annotations

from typing import Any


OBSERVED_E01_5_ROLES = [
    "checklist_step_01_clipboard",
    "checklist_step_02_valve",
    "checklist_step_03_gauge",
    "checklist_step_04_shield",
    "checklist_step_05_document_pencil",
    "chevron_step_01",
    "chevron_step_02",
    "chevron_step_03",
    "chevron_step_04",
    "chevron_step_05",
    "bottom_warning_ppe",
    "bottom_hardhat_ppe",
    "bottom_lock_zero_leak",
    "bottom_chemical_barrier_shield",
    "bottom_communicate_chat",
    "bottom_teamwork_users",
]


ROLE_FAMILIES: dict[str, list[str]] = {
    "document_evidence": [
        "document",
        "file_text",
        "checklist",
        "clipboard_check",
        "report",
        "citation",
        "source",
        "archive",
        "folder",
        "book",
        "note",
        "edit_pencil",
        "file_check",
        "file_plus",
        "document_search",
    ],
    "data_analytics": [
        "database",
        "table",
        "chart_bar",
        "chart_line",
        "pie_chart",
        "dashboard",
        "kpi",
        "trend_up",
        "trend_down",
        "metric",
        "filter",
        "search",
        "analytics",
        "calculator",
        "percent",
    ],
    "risk_governance": [
        "shield",
        "shield_check",
        "warning",
        "alert_triangle",
        "lock",
        "key",
        "scale",
        "gavel",
        "policy",
        "compliance",
        "approval",
        "exception",
        "certificate",
        "ban",
        "eye_check",
    ],
    "process_workflow": [
        "workflow",
        "route",
        "process_node",
        "decision_diamond",
        "timeline",
        "flag",
        "target",
        "refresh",
        "loop",
        "package",
        "launch",
        "arrow_right",
        "flow",
        "branch",
        "repeat",
    ],
    "people_ownership": [
        "user",
        "users",
        "owner",
        "council",
        "team",
        "handshake",
        "reviewer",
        "user_check",
        "user_star",
        "group",
        "briefing",
        "person_alert",
    ],
    "technology_ai": [
        "brain",
        "chip",
        "network",
        "nodes",
        "server",
        "cloud",
        "model",
        "automation",
        "settings",
        "robot",
        "cpu",
        "api",
        "code",
        "sparkles",
        "layers",
    ],
    "business_institution": [
        "building",
        "bank",
        "factory",
        "globe",
        "briefcase",
        "trophy",
        "star",
        "anchor",
        "store",
        "chart_presentation",
    ],
    "ui_navigation": [
        "chevron_right",
        "chevron_left",
        "arrow_right",
        "arrow_down",
        "plus",
        "minus",
        "check",
        "close",
        "calendar",
        "clock",
        "menu",
        "info",
        "help",
        "download",
        "upload",
    ],
    "current_e01_5_observed": OBSERVED_E01_5_ROLES,
}


ROLE_ALIASES: dict[str, list[str]] = {
    "document": ["file", "file-text", "article", "notes"],
    "file_text": ["file-text", "file-description", "article"],
    "checklist": ["checklist", "list-check", "clipboard-check", "list-details"],
    "clipboard_check": ["clipboard-check", "clipboard-list", "clipboard-text"],
    "report": ["report", "file-report", "license"],
    "citation": ["quote", "quotes", "reference"],
    "source": ["database", "database-search", "quote"],
    "archive": ["archive", "box", "archive-filled"],
    "folder": ["folder", "folder-open"],
    "book": ["book", "book-2"],
    "note": ["note", "notes", "notebook"],
    "edit_pencil": ["edit", "pencil", "pencil-plus"],
    "file_check": ["file-check", "file-certificate"],
    "file_plus": ["file-plus"],
    "document_search": ["file-search", "search"],
    "database": ["database"],
    "table": ["table"],
    "chart_bar": ["chart-bar", "chart-infographic"],
    "chart_line": ["chart-line", "chart-arrows"],
    "pie_chart": ["chart-pie", "chart-donut"],
    "dashboard": ["dashboard", "layout-dashboard"],
    "kpi": ["speedometer", "gauge", "dashboard"],
    "trend_up": ["trending-up", "trend-up"],
    "trend_down": ["trending-down", "trend-down"],
    "metric": ["gauge", "meter", "chart-arcs"],
    "filter": ["filter"],
    "search": ["search"],
    "analytics": ["chart-dots", "chart-histogram", "activity"],
    "calculator": ["calculator"],
    "percent": ["percentage", "percent"],
    "shield": ["shield"],
    "shield_check": ["shield-check", "shield-half"],
    "warning": ["alert-triangle", "alert-circle"],
    "alert_triangle": ["alert-triangle"],
    "lock": ["lock", "lock-check"],
    "key": ["key"],
    "scale": ["scale"],
    "gavel": ["gavel", "hammer"],
    "policy": ["license", "file-certificate", "contract"],
    "compliance": ["shield-check", "certificate"],
    "approval": ["circle-check", "check"],
    "exception": ["exclamation-circle", "alert-circle"],
    "certificate": ["certificate", "rosette"],
    "ban": ["ban", "circle-off"],
    "eye_check": ["eye-check", "eye"],
    "workflow": ["git-branch", "workflow", "sitemap"],
    "route": ["route"],
    "process_node": ["node", "circle-dot", "git-commit"],
    "decision_diamond": ["diamond", "git-compare"],
    "timeline": ["timeline"],
    "flag": ["flag"],
    "target": ["target"],
    "refresh": ["refresh", "rotate"],
    "loop": ["repeat", "arrows-repeat"],
    "package": ["package"],
    "launch": ["rocket", "send"],
    "arrow_right": ["arrow-right"],
    "flow": ["route", "arrows-diff"],
    "branch": ["git-branch"],
    "repeat": ["repeat", "refresh"],
    "user": ["user"],
    "users": ["users"],
    "owner": ["user-check", "user-star"],
    "council": ["users-group", "users"],
    "team": ["users", "friends"],
    "handshake": ["handshake"],
    "reviewer": ["user-scan", "user-check"],
    "user_check": ["user-check"],
    "user_star": ["user-star"],
    "group": ["users-group", "users"],
    "briefing": ["presentation", "chalkboard"],
    "person_alert": ["user-exclamation", "alert-circle"],
    "brain": ["brain"],
    "chip": ["cpu", "chip"],
    "network": ["network", "topology-star"],
    "nodes": ["nodes", "sitemap"],
    "server": ["server"],
    "cloud": ["cloud"],
    "model": ["device-desktop-analytics", "brain"],
    "automation": ["automation", "settings-automation", "robot"],
    "settings": ["settings"],
    "robot": ["robot"],
    "cpu": ["cpu"],
    "api": ["api", "plug-connected"],
    "code": ["code"],
    "sparkles": ["sparkles", "stars"],
    "layers": ["layers-intersect", "stack"],
    "building": ["building"],
    "bank": ["building-bank", "bank"],
    "factory": ["building-factory", "factory"],
    "globe": ["world", "globe"],
    "briefcase": ["briefcase"],
    "trophy": ["trophy"],
    "star": ["star"],
    "anchor": ["anchor"],
    "store": ["building-store", "store"],
    "chart_presentation": ["presentation-analytics", "presentation"],
    "chevron_right": ["chevron-right"],
    "chevron_left": ["chevron-left"],
    "arrow_down": ["arrow-down"],
    "plus": ["plus"],
    "minus": ["minus"],
    "check": ["check"],
    "close": ["x", "close"],
    "calendar": ["calendar"],
    "clock": ["clock"],
    "menu": ["menu-2", "menu"],
    "info": ["info-circle", "info"],
    "help": ["help-circle", "question-mark"],
    "download": ["download"],
    "upload": ["upload"],
    "checklist_step_01_clipboard": ["checklist_step_01_clipboard", "clipboard-check"],
    "checklist_step_02_valve": ["checklist_step_02_valve", "valve", "pipeline"],
    "checklist_step_03_gauge": ["checklist_step_03_gauge", "gauge"],
    "checklist_step_04_shield": ["checklist_step_04_shield", "shield-check"],
    "checklist_step_05_document_pencil": ["checklist_step_05_document_pencil", "file-pencil", "file-text"],
    "bottom_warning_ppe": ["bottom_warning_ppe", "alert-triangle"],
    "bottom_hardhat_ppe": ["bottom_hardhat_ppe", "helmet", "hardhat"],
    "bottom_lock_zero_leak": ["bottom_lock_zero_leak", "lock"],
    "bottom_chemical_barrier_shield": ["bottom_chemical_barrier_shield", "shield-check"],
    "bottom_communicate_chat": ["bottom_communicate_chat", "message-check"],
    "bottom_teamwork_users": ["bottom_teamwork_users", "users"],
}


def build_curated_icon_role_taxonomy_v2() -> dict[str, Any]:
    roles = []
    high_priority_budget = 64
    for family, family_roles in ROLE_FAMILIES.items():
        for role in family_roles:
            roles.append(
                {
                    "role": role,
                    "family": family,
                    "aliases": ROLE_ALIASES.get(role, [role.replace("_", "-"), role]),
                    "search_keywords": _keywords(role, ROLE_ALIASES.get(role, [])),
                    "required": True,
                    "high_priority": len(roles) < high_priority_budget or role in OBSERVED_E01_5_ROLES,
                    "preferred_variant": "outline",
                }
            )
    return {
        "schema_name": "curated_icon_role_taxonomy_v2",
        "status": "passed",
        "total_role_count": len(roles),
        "high_priority_role_count": sum(1 for role in roles if role["high_priority"]),
        "minimum_required_role_count": 96,
        "minimum_high_priority_role_count": 48,
        "observed_e01_5_roles": OBSERVED_E01_5_ROLES,
        "families": [{"family": name, "role_count": len(values)} for name, values in ROLE_FAMILIES.items()],
        "roles": roles,
        "canva_parity_claimed": False,
    }


def observed_e01_5_roles() -> list[str]:
    return list(OBSERVED_E01_5_ROLES)


def _keywords(role: str, aliases: list[str]) -> list[str]:
    tokens = [role, role.replace("_", "-"), *aliases]
    keywords: list[str] = []
    for token in tokens:
        for part in token.replace("-", "_").split("_"):
            if part and part not in keywords:
                keywords.append(part)
    return keywords
