"""P0/P1 icon role taxonomy for the E03.4 icon foundation gate."""

from __future__ import annotations

from typing import Any


P0_ROLE_IDS = (
    "source",
    "citation",
    "document",
    "file_check",
    "checklist",
    "clipboard_check",
    "database",
    "table",
    "chart_bar",
    "chart_line",
    "pie_chart",
    "dashboard",
    "kpi",
    "shield",
    "shield_check",
    "warning",
    "risk_status",
    "lock",
    "approval",
    "decision_diamond",
    "process_node",
    "timeline",
    "milestone_flag",
    "flag",
    "target",
    "route",
    "network",
    "calendar",
    "clock",
    "user",
    "users",
    "team",
    "owner",
    "note",
    "insight",
    "recommendation",
    "next_action",
    "evidence_trace",
    "scale",
    "book",
    "folder",
    "layers",
)

P1_ROLE_IDS = (
    "building",
    "bank",
    "factory",
    "api",
    "automation",
    "brain",
    "chip",
    "model",
    "cloud",
    "server",
    "filter",
    "search",
    "refresh",
    "loop",
    "package",
    "launch",
    "gavel",
    "trophy",
    "star",
    "anchor",
    "globe",
    "handshake",
    "help",
    "info",
)

ROLE_FAMILIES = {
    "source": "source_citation",
    "citation": "source_citation",
    "document": "document_record",
    "file_check": "document_record",
    "checklist": "document_record",
    "clipboard_check": "document_record",
    "database": "data_table_chart",
    "table": "data_table_chart",
    "chart_bar": "data_table_chart",
    "chart_line": "data_table_chart",
    "pie_chart": "data_table_chart",
    "dashboard": "data_table_chart",
    "kpi": "data_table_chart",
    "shield": "risk_control",
    "shield_check": "risk_control",
    "warning": "risk_control",
    "risk_status": "risk_control",
    "lock": "risk_control",
    "approval": "decision_action",
    "decision_diamond": "decision_action",
    "process_node": "process_timeline",
    "timeline": "process_timeline",
    "milestone_flag": "process_timeline",
    "flag": "process_timeline",
    "target": "process_timeline",
    "route": "process_timeline",
    "network": "systems",
    "calendar": "time_people",
    "clock": "time_people",
    "user": "time_people",
    "users": "time_people",
    "team": "time_people",
    "owner": "time_people",
    "note": "insight_synthesis",
    "insight": "insight_synthesis",
    "recommendation": "insight_synthesis",
    "next_action": "insight_synthesis",
    "evidence_trace": "evidence",
    "scale": "evidence",
    "book": "knowledge",
    "folder": "knowledge",
    "layers": "knowledge",
    "building": "business_context",
    "bank": "business_context",
    "factory": "business_context",
    "api": "systems",
    "automation": "systems",
    "brain": "systems",
    "chip": "systems",
    "model": "systems",
    "cloud": "systems",
    "server": "systems",
    "filter": "workflow",
    "search": "workflow",
    "refresh": "workflow",
    "loop": "workflow",
    "package": "workflow",
    "launch": "workflow",
    "gavel": "decision_action",
    "trophy": "decision_action",
    "star": "decision_action",
    "anchor": "decision_action",
    "globe": "business_context",
    "handshake": "business_context",
    "help": "support",
    "info": "support",
}

VISUAL_DESCRIPTIONS = {
    "source": "database or origin marker with source provenance cue",
    "citation": "link or quotation/citation marker",
    "document": "folded-corner document sheet",
    "file_check": "document sheet with check mark",
    "checklist": "stacked checklist lines with ticks",
    "clipboard_check": "clipboard board with check mark",
    "database": "stacked cylinder database",
    "table": "editable grid/table mark",
    "chart_bar": "bar chart with axis",
    "chart_line": "line chart with trend",
    "pie_chart": "pie/donut chart split",
    "dashboard": "dashboard panels or gauge tiles",
    "kpi": "metric tile with upward emphasis",
    "shield": "security/control shield",
    "shield_check": "shield with check mark",
    "warning": "warning triangle with exclamation",
    "risk_status": "risk status diamond/star marker",
    "lock": "padlock",
    "approval": "approval check or badge",
    "decision_diamond": "decision diamond",
    "process_node": "process node circle or rounded node",
    "timeline": "timeline axis with milestone points",
    "milestone_flag": "timeline milestone flag",
    "flag": "flag marker",
    "target": "target rings",
    "route": "route/path with nodes",
    "network": "connected network nodes",
    "calendar": "calendar page",
    "clock": "clock face",
    "user": "single person",
    "users": "two person group",
    "team": "team group",
    "owner": "person with ownership badge",
    "note": "note page or sticky note",
    "insight": "lightbulb or insight spark",
    "recommendation": "recommendation check and action line",
    "next_action": "forward arrow action marker",
    "evidence_trace": "eye/traceability marker",
    "scale": "balance scale",
    "book": "open book",
    "folder": "folder",
    "layers": "stacked layers",
}

ALIASES = {
    "source": ["origin", "data_source", "provenance"],
    "citation": ["link", "reference", "quote"],
    "file_check": ["approved_file", "validated_document"],
    "clipboard_check": ["audit_check", "task_check"],
    "chart_bar": ["bar_chart", "bar"],
    "chart_line": ["line_chart", "trend"],
    "pie_chart": ["donut", "share"],
    "decision_diamond": ["decision", "gate"],
    "process_node": ["process", "step_node"],
    "milestone_flag": ["milestone", "phase_flag"],
    "evidence_trace": ["trace", "evidence"],
    "next_action": ["action", "next_step"],
    "api": ["endpoint", "integration"],
}


def build_p0_p1_icon_role_taxonomy() -> dict[str, Any]:
    roles = [_role_entry(role_id, "P0_REQUIRED_SEMANTIC") for role_id in P0_ROLE_IDS]
    roles.extend(_role_entry(role_id, "P1_HIGH_REUSE") for role_id in P1_ROLE_IDS)
    return {
        "schema_name": "p0_p1_icon_role_taxonomy",
        "status": "passed",
        "p0_role_count": len(P0_ROLE_IDS),
        "p1_role_count": len(P1_ROLE_IDS),
        "role_count": len(roles),
        "roles": roles,
        "roles_by_role": {row["role_id"]: row for row in roles},
    }


def _role_entry(role_id: str, priority: str) -> dict[str, Any]:
    family = ROLE_FAMILIES.get(role_id, "general")
    label = role_id.replace("_", " ")
    return {
        "role_id": role_id,
        "family": family,
        "aliases": sorted(set(ALIASES.get(role_id, []) + [label])),
        "visual_description": VISUAL_DESCRIPTIONS.get(role_id, f"{label} pictogram with role-specific silhouette"),
        "allowed_shape_primitives": ["path", "line", "polyline", "circle", "rect", "ellipse", "polygon"],
        "forbidden_generic_substitutes": ["plus", "plain_circle", "plain_square", "blank", "role_label_text"],
        "acceptable_curated_source": "assets/icons/curated/magic_layer_v7",
        "expected_small_size_legibility": "recognizable at 16px and clear at 24px",
        "usage_contexts": _usage_contexts(role_id, family),
        "priority": priority,
    }


def _usage_contexts(role_id: str, family: str) -> list[str]:
    contexts = {
        "source_citation": ["source/footer strip", "citation rail", "evidence panel"],
        "document_record": ["record panel", "card icon zone", "decision metadata"],
        "data_table_chart": ["dashboard KPI", "chart frame", "table header", "matrix header"],
        "risk_control": ["risk register", "control status", "security note"],
        "decision_action": ["decision record", "recommendation block", "approval module"],
        "process_timeline": ["process flow", "timeline roadmap", "methodology framework"],
        "time_people": ["metadata rail", "owner row", "timeline note"],
        "insight_synthesis": ["insight rail", "closing synthesis", "takeaway card"],
        "evidence": ["evidence overview", "traceability strip", "comparison scoring"],
        "systems": ["technical overlay", "architecture card", "automation module"],
        "workflow": ["process card", "action panel", "filter/search utility"],
    }.get(family, ["template semantic icon zone"])
    if role_id in {"api", "server", "cloud", "model", "chip"}:
        contexts.append("technical system card")
    return contexts
