"""Fail-closed Phase 4A external-execution contracts."""

from .acceptance import (
    ACCEPTANCE_HASH_DOMAIN,
    ACCEPTANCE_POLICY_ID,
    AcceptancePreconditionError,
    ExternalExecutionAcceptance,
    compute_acceptance_record_hash,
    evaluate_external_execution_acceptance,
    verify_acceptance_record,
)
from .contracts import (
    APPROVED_EXTERNAL_EXECUTABLE_IDS,
    ExternalExecutableAdapter,
    ExternalExecutableAuthorizationError,
    ExternalExecutionRequest,
    ExternalReferenceInput,
    ExternalTransport,
    authorize_external_executable_id,
    build_external_execution_request,
    canonical_request_bytes,
    compute_request_semantic_id,
    compute_request_semantic_sha256,
)
from .openai_adapter import ExternalExecutionDisabledError, OpenAIAdapterSkeleton
from .record import (
    BLOCKED_REASON,
    EXECUTION_RECORD_HASH_DOMAIN,
    OUTPUT_HASH_DOMAIN,
    RESPONSE_HASH_DOMAIN,
    REQUEST_HASH_DOMAIN,
    ExecutionRecordImmutableError,
    ExecutionRecordPathError,
    ExternalExecutionRecord,
    HashBinding,
    build_blocked_execution_record,
    build_hash_binding,
    canonical_execution_record_bytes,
    compute_execution_record_hash,
    write_execution_record,
)
from .verification import (
    VERIFICATION_REPORT_HASH_DOMAIN,
    ExternalExecutionVerificationReport,
    compute_verification_report_hash,
    verify_external_execution_record,
    verify_hash_binding,
)

__all__ = [
    "ACCEPTANCE_HASH_DOMAIN",
    "ACCEPTANCE_POLICY_ID",
    "APPROVED_EXTERNAL_EXECUTABLE_IDS",
    "BLOCKED_REASON",
    "EXECUTION_RECORD_HASH_DOMAIN",
    "OUTPUT_HASH_DOMAIN",
    "RESPONSE_HASH_DOMAIN",
    "REQUEST_HASH_DOMAIN",
    "VERIFICATION_REPORT_HASH_DOMAIN",
    "AcceptancePreconditionError",
    "ExecutionRecordImmutableError",
    "ExecutionRecordPathError",
    "ExternalExecutableAdapter",
    "ExternalExecutableAuthorizationError",
    "ExternalExecutionAcceptance",
    "ExternalExecutionDisabledError",
    "ExternalExecutionRecord",
    "ExternalExecutionRequest",
    "ExternalExecutionVerificationReport",
    "ExternalReferenceInput",
    "ExternalTransport",
    "HashBinding",
    "OpenAIAdapterSkeleton",
    "authorize_external_executable_id",
    "build_blocked_execution_record",
    "build_external_execution_request",
    "build_hash_binding",
    "canonical_execution_record_bytes",
    "canonical_request_bytes",
    "compute_acceptance_record_hash",
    "compute_execution_record_hash",
    "compute_request_semantic_id",
    "compute_request_semantic_sha256",
    "compute_verification_report_hash",
    "evaluate_external_execution_acceptance",
    "verify_acceptance_record",
    "verify_external_execution_record",
    "verify_hash_binding",
    "write_execution_record",
]
